GET http://localhost:3002/rol
########

POST http://localhost:3002/rol/
Content-Type: application/json

{

    "descripcion": "gia llora"
}
###

PUT http://localhost:3002/universidad/
Content-Type: application/json

{
    "idUniversidad": 2, 
    "descripcion": "Universidad Pacifico"
}

###

GET http://localhost:3002/universidad/2
###

DELETE http://localhost:3002/universidad/1